### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by HADDADENICAR** [huashiyiqike/GeoHash_Neo4j#1]
Hello,
How to install your plugin ?
i downloaded it and i zipped it in the plugin folder, then i restart neo4j but apparently it haven't been installed !?

**Comment by huashiyiqike** [comment]
see readme, this is not a plugin

**Comment by HADDADENICAR** [comment]
can you clarify more please ? 
i m new to neo4j. i saw you readme and it is not clear for me .
if it is not a plugin then what it is ?

**Comment by HADDADENICAR** [comment]
Don't know if it's too late. Recently I have implemented a trie based neo4j
geohash plugin at https://github.com/huashiyiqike/GeoHash_Neo4j. It is easy
to understand (i found it   [here](http://grokbase.com/t/gg/neo4j/157wr7veh6/neo4j-and-geo-hashes))
